# Use an official Node runtime as the base image
FROM node:16

# Set the working directory in the container
WORKDIR /app

# Copy package.json and package-lock.json to the working directory
COPY package*.json ./

# Install the frontend dependencies
RUN npm install

# Copy all source files from the host to the working directory in the container
COPY . .

# Start the frontend development server
CMD ["npm", "start"]
