# Use an official Python runtime as the base image
FROM python:3.11.1

# Set the working directory in the container
WORKDIR /app

# Copy the requirements file to the working directory
COPY requirements.txt ./

# Install the backend dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Copy all source files from the host to the working directory in the container
COPY . .

# Start the backend server
CMD ["python", "main.py"]
